# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "db/migrations/"

[print_schema]
file = "db/src/schema.rs"
import_types = ["crate::sql_types::*"]

